- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/package.json
This update requires that the developer be on the latest version of node and npm.
> Updated to the latest node versions to eliminate dependency errors

- core/dslmcode/profiles/cis-7.x-2.x/modules/features/cis_displays/cis_displays.views_default.inc
- core/dslmcode/profiles/cis-7.x-2.x/modules/features/cis_types/cis_types.features.field_base.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views/includes/handlers.inc
I have fixed the Features Warning Notice: Undefined index: group in views_handler->ui_name() that was displayed when going to the 'Create New Feature' page. The problem was that the legacy field
field_internal_classification     
was still being used in the cis-7.x-2.x source code. Removing lines that reference the old variable the Warning Notice goes away and the issue is resolved.
> Fixed Features Warning Notice: Undefined index: group in views_handler->ui_name() #268

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/features/cis_section/cis_section.module
What if we just used the `cis_section_all_sections()` function to gather the list of allowed sections for this user?  That aligns it more with how the rest of the section switching works.
> Change method of allowed sections for user.

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/mooc_helper_book_nav.module
Now now that we've added a menu callback `mooc/book-homepage` that dynaimcally switches the homepage depending on what section you are in, we need to allow empty pages redirects on the homepage.
> Allow empty book outline pages to be the homepage.

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/bower.json
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/app.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/hologram_config.yml
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/app.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/components/_buttons.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/components/_clipboard.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/main-styles/_common.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/regions/_r-header.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_buttons.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_clipboard.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_figurelabel.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_image.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_mediasvg.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_quote.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_mediavideo.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/index.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/widgets_imagelightbox.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/template.php
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/clipboardjs/clipboardjs.tpl.php
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/system/page.tpl.php
- Added material design icons
- fixed r-header z-index so it doesn't cover up admin bar or lightboxes
- Rordered r-header icons
- r-header is less jerky when going to sticky
- Added button design component
- Styled clipboardjs button with new button component
> UI Improvements for header region and copy to clipboard button

- core/dslmcode/profiles/eph-7.x-1.x/drupal-org.make
- core/dslmcode/stacks/hub/profiles/README.txt
- scripts/developer/README.txt
- scripts/install/elmsln-install.sh
Well that was weird. D 7.41 core introduced a README.txt file which dslm naturally auto symlinked in our create-new-tool.sh script. Then the installer thought it was another profile that we needed to rip into our installer... which would never work :)
> Make HUB work

- docs/development/Vagrant-Step-by-Step-setup.md
Reorganized the vagrant plugin information a bit to understand why you might install the plugins (so people don't have to just install them blindly or search far and wide to determine if they _really_ want to install a plugin). Should satisfy issue #579
> more vagrant plugin information

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/cis_connector.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/cis_filter.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/templates/cis-filter-contextual-links.tpl.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/templates/contextual-container.tpl.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/elmsln_api/callbacks/v1/clear_cache_bin.inc
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/elmsln_api/elmsln_api.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_core/elmsln_core.module
- core/dslmcode/stacks/grades/sites/all/modules/contrib/quiz_ddlines/js/quiz_ddlines.js
This branch brings in contextual links on all rendered shortcodes for developers / faculty / admins. Once media (for example) is placed in the content outline, if you hover over the media while viewing the content in the content outline you'll get a windy wheel to view / edit that item. This then links over to the appropriate system / content where you can make changes (if editing). Then on the return it frags the cached item reference meaning that you (and others) see the change reflected immediately without caching penalty.
This improves our cache tag granularity as well meaning we can remove things by asking to delete `elmsln:cis:node` which would delete all of the cached calls that were for nodes from CIS. also this could get to specific entity ids like …
> #941 maintain course context across systems AND do contextual links

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_content_theming/mooc_content_theming.features.field_instance.inc
This fixes the issue of `-None-` not being the default for `field_instructional_significance`. Instructors will now have to choose the significance instead of having a `Page` specified by default.
> #1001 Removed Default Value

- scripts/install/root/elmsln-preinstall.sh
This pull request is related to #987 
There are still some errors related to:
```
ln: failed to create symbolic link ‘/usr/share/drush’: File exists
unlink(/root/.config/composer/vendor/drush/drush/lib/package.xml): No[warning]
such file or directory drush.inc:691
'drush' cache was cleared.                                                                                                                                        [success]
groupadd: group 'elmsln' already exists
cp: cannot stat ‘/root/.composer’: No such file or directory
```
where now composer, when installed by root is in /root/.config/composer
and
```
/var/www/elmsln/scripts/install/users/elmsln-admin-user.sh: line 61: drush: command not found
/var/www/elmsln/scripts/install/users/elmsln-admin-user.sh: line 63: drush: command …
```
> Root composer drush fix

- core/dslmcode/profiles/icor-7.x-1.x/modules/features/icor_defaults/icor_defaults.install
- core/dslmcode/profiles/icor-7.x-1.x/modules/features/icor_defaults/icor_defaults.views_default.inc
- core/dslmcode/profiles/icor-7.x-1.x/modules/features/icor_interactive_player/icor_interactive_player.install
- core/dslmcode/profiles/icor-7.x-1.x/modules/features/icor_interactive_player/icor_interactive_player.views_default.inc
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/authorities/cis_course_authority/cis_course_authority.install
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/authorities/cis_course_authority/cis_course_authority.views_default.inc
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/cis_section/cis_section.install
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/cis_section/cis_section.views_default.inc
- core/dslmcode/stacks/interact/sites/all/modules/local_contrib/views_timelinejs/views_timelinejs.install
- core/dslmcode/stacks/interact/sites/all/modules/local_contrib/views_timelinejs/views_timelinejs_feature/views_timelinejs_feature.views_default.inc
- core/dslmcode/stacks/interact/sites/all/modules/local_contrib/views_timelinejs_extras/views_timelinejs_extras.install
- core/dslmcode/stacks/interact/sites/all/modules/local_contrib/views_timelinejs_extras/views_timelinejs_extras.views_default.inc
Caching is now active for Interact. Added update hooks for each of the files that were changed. Issue: `CIS User List` does not seem to exist in our CIS folder structure. Details of the caching times are listed below:
Interact Choices:
#1055
> #1036 Interact Caching Choices

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/materialize_actions/materialize_actions.api.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/materialize_actions/materialize_actions.info
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/materialize_actions/materialize_actions.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/materialize_actions/modules/materialize_actions_logins/materialize_actions_logins.info
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/materialize_actions/modules/materialize_actions_logins/materialize_actions_logins.module
To use this module you can create a new status message.
```
drupal_set_message('Hey!', 'notification');
```
Ignore the materialize_actions_logins module.
> Materialize actions

- scripts/vagrant/handsfree-vagrant.sh
basically the proper elevated permissions weren't being set after the rhel7/centos7 update occurred. While this isn't the perfect or most elegant solution it fixes the problem without disrupting anything system wide.
> fixes centos7 drush and group issues

- scripts/install/root/elmsln-preinstall.sh
- scripts/server/my.txt
This luckily makes more sense than having to create an extra my.txt file.
Premise being that in probably the oldest we would have to support (rhel6) this works since the naming of table_cache to table_open_cache was backported.
> Solves the my.cnf issue

- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/book_copy/book_copy.module
This uses batch api and only looks for exact matches when replacing node ids. 
It processes 5 nodes at a time and won't act on 300 when 30 is the target.
> Allow Book Copy to update internal links in body

- scripts/install/handsfree/centos/example-deploy
When I've tried installing, can't get the epel repo until you get the remi one. So swapped them in the installation order
> Installation Order - swap epel and remi

- scripts/install/handsfree/ubuntu16/ubuntu16-install.sh
This will fix the ubuntu side of things for yaml and ldap the rhel side was fixed in https://github.com/elmsln/php56-fpm-centos7-mysql56/commit/b85227575ba22c47ff50e973f7f8496a79885099
Fixes #1533
Fixes #1429
> support yaml and ldap

- core/dslmcode/shared/drupal-7.x/libraries/chosen/PATCHES.txt
Fixes #
Made PATCHES.txt in case future developers notice we changed the chosen library without a patch. This is due to the chosen library on GitHub not supporting the file we patched in its version control as it migrated to coffeescript.
> #1532 Documented Change to chosen library

- core/dslmcode/profiles/elmsmedia-7.x-1.x/elmsmedia.install
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_audio/elmsmedia_audio.features.field_instance.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_audio/elmsmedia_audio.info
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_document/elmsmedia_document.features.field_instance.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_external_video/elmsmedia_external_video.features.field_instance.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_external_video/elmsmedia_external_video.info
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_feature/elmsmedia_feature.features.field_base.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_feature/elmsmedia_feature.info
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_image/elmsmedia_image.features.field_instance.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_video/elmsmedia_video.features.field_instance.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_video/elmsmedia_video.info
Fixes #
Media now supports multiple courses to be selected for what course it should go in. Files affected by this change feature override:
audio
document
external_video
feature
image
> #1298 Support Multiple Course Selection for Media Content

- Vagrantfile
- scripts/install/handsfree/ubuntu16/ubuntu16-install.sh
- scripts/vagrant/cleanup.sh
- scripts/vagrant/handsfree-vagrant.sh
Here goes nothing...
If I have access to the docs I am not sure how to edit. But https://elmsln.readthedocs.io/en/latest/development/Vagrant-Step-by-Step-setup/ needs to be edited to reflect new minimum versions of Vagrant and VirtualBox
Vagrant = 1.9.1
VirtualBox = 5.1.10
> Vagrant now uses ubuntu 16.04

- core/dslmcode/shared/drupal-7.x/settings/shared_settings.php
Addresses #1610 but doesn't resolve it. 
Drupal overrides php.ini settings so we need to re-override them
> Drupal sets custom error settings.

- docs/lrs/LearningLocker.md
Issue with bad encoding of quotation marks and missing semi-colon.
This will make it easier to copy/paste the code
> Fix quotation mark encoding and missing semi-colon

- docs/development/Vagrant-Step-by-Step-setup.md
Windows users can use git download shell for unix commands if they do not have built in unix support.
Fixes #
> #1853 Windows Clarification

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/template.php
Fixes #1946 -- Adjusted logic for how the poster is generated in the mediavideo view mode.
> External Video Posters not working for mediavideo

- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_critique/cle_critique.module
This will prevent submissions from being critiqued if they are not set to 'submission_ready'
> Studio Critique change

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/css/mooc_styles.css
Request to bump to the font-size down a hair to allow more room for the page titles.
> tweaks to mooc toolbar.

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/css/mooc_styles.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
Wanted to try to fit more text in menu links and add some slight animations during the "pinning" process.
I think we could probably make it more "paper" style in the future and take advantage of the box shadows.
> Added transition for pinned sidenav. reduced font-size.

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/css/mooc_styles.css
> Mooc nav icons overlay text #2005

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/mooc_helper_book_nav.module
The auto advance will now check the current page is of type book with an empty body field OR of type git_book.  Both will result in true and advance the page for a person who doesn't have permission to edit the page.
Fixes #2007
> Gitbook Auto advance

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
I added .image selector to tweaks.css line 1696; this allows 'citation field' the ability to display inline.
Fixes #2013
> Citation field input wraps instead of displaying inline 

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_simple_filter/elmsln_simple_filter.features.filter.inc
Checked "Convert URLs into links" for Simple text format and exported into feature. This should resolve the feature request from issue 2012 below.
Fixes #
2012 (https://github.com/elmsln/elmsln/issues/2012)
Please let me know how to better submit pull requests (tried to follow contributing.md) in the future.
Thanks.
-Nate
> Add hyperlink functionality to simple text format #2012 -- Pull request

- README.md
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_simple_filter/elmsln_simple_filter.features.filter.inc
PR against 0.9.x instead of master per btopro (https://github.com/elmsln/elmsln/pull/2053).
Checked "Convert URLs into links" for Simple text format and exported into feature. This should resolve the feature request from issue 2012 below.
Fixes #
2012 (#2012)
Please let me know how to better submit pull requests (tried to follow contributing.md) in the future.
Thanks.
-Nate
> Add hyperlink functionality to simple text format #2012 -- Pull request (take 2)

- docs/development/front-end/Fonts.md
- docs/development/front-end/Front-End-Development-Workflow.md
- docs/development/front-end/Styleguide.md
In reading through the front-end docs, I noticed a couple of links that were 404ing & and path that needed to be updated. These are very small changes to the documentation.
> Update docs frontend paths broken

- scripts/install/handsfree/ubuntu16/ubuntu16-install.sh
Couldn't install h5p libraries at http://media.elmsln.local/admin/content/h5p. zip & mbstring packages were missing. 
I can confirm that a clean vagrant up (with this commit) allows for installing h5p libraries. Reviewing all of the packages would be a good idea, but it is beyond me.
Fixes #1911
> H5P can't download/upload .h5p files w/o updated packages

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/legacy/js/app.js
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/legacy/js/dist/app.js
I added new setting to check the window vs document heights. The if statement is used to determine if the scrollbar should be shown on the screen. 
Currently 50 is the magic number. This means that a page that is twice as long as the monitor display will show the scrollbar. 50 could be changed to 33.3 if the scrollbar should only be shown on pages that are three times longer than the monitor height.
- legacy/js/dist/app.js is the code that is run. I added code to both files in case I'm missing something.
Fixes #2001
> Hide horizontal scrollbar on short pages

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/webcomponents/README.md
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/webcomponents/modules/webcomponents_app/webcomponents_app.module
Fixes #2079 
When the `_webcomponents_app_load_app_data` function is attempting to find the matching path, it will treat routes defined with the `%` placeholder as wildcard or dynamic routes.
So if it's evaluating the path `apps/phone-book/api/numbers/555-5555` it will match it to the `api/numbers/%` route that was defined in the apps `endpoints` object within the manifest.json file.
> Added Wildcard Routes to Webcomponents module

- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_h5p/elmslnmedia_h5p.api.php
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_h5p/elmsmedia_h5p.install
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_h5p/elmsmedia_h5p.module
This allows you to add whitelisted tags that will be rendered in h5p text areas. You add tags via `elmsln_h5p_allowed_tags` variable or with `hook_elmsln_h5p_allowed_tags_alter`.
This has only been tested with H5P Single Choice Option.
Fixes #2087
> Render web components in H5P text fields

- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/README.md
- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/git_book.drush.inc
- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/git_book.module
- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/modules/git_book_gb/git_book_gb.module
Fixes #2088
Added a gitbook sync feature.  You can run `git-book-sync [name_of_book]` and it will pull changes from origin and run the parser to either create or updated content in the drupal book.
I also added to git config changes when creating the repo to minimize erroneous merge conflicts:
```
$repo->run('config core.fileMode false');
$repo->run('config core.autocrlf false');
```
There is one outstanding issue that I'm not sure how to solve, #2088.  However, if you manually clean up permissions with `leafy` after running the drush commands it works fine.
> Add Gitbook sync feature 2009

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/main.css
Updates line 2945 of main.css for ul, ol, dl font-size and line-height to match p.
Fixes #2144
> Bullet and Number Lists Styling

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/main.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/materialize_unwinding/css/materialize.css
`ul:not(.browser-default) {
padding-left: 0;
list-style-type: none;
}
ul:not(.browser-default) li {
list-style-type: none;
}`
Removing this snippet allows there to an indent on the bulleted lists, and adds bullets and indent while in the editor state.
Fixes #2144
> removed css materialize.css

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/ckeditor_custom_config.js
Related to issue #2302
Fix for an issue where HTML comments entered into CKEditor Source View would cut off content when switching back to WYSIWYG mode. Includes HTML comments and keeps previous support for WebComponents.
> Include HTML Comments in CKEditor Protected Source

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/ckeditor_custom_config.js
Related to issue #2302 and an update to pull request #2305
This adds in a few characters to ensure that original webcomponent support still works.
**Original (#2305) PR message**
Fix for an issue where HTML comments entered into CKEditor Source View would cut off content when switching back to WYSIWYG mode. Includes HTML comments and keeps previous support for WebComponents.
> Update to CKEditor custom config

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/template.php
From what I see, it looks like the permissions should be the same.
Fixes #2371
> removed ‘staff’ specification for add media links. #2371

- core/dslmcode/stacks/discuss/sites/all/modules/local_contrib/harmony_core/theme/harmony-post.tpl.php
- core/dslmcode/stacks/discuss/sites/all/modules/local_contrib/harmony_core/theme/harmony-profile-image.patch
- core/dslmcode/stacks/discuss/sites/all/modules/local_contrib/harmony_core/theme/theme.inc
This PR contains a tweak to the harmony discussion core which 
Removing the profile image from discussion posts and replacing it with the username of the poster. Default link added to make it match in with local styling.
It definitely a bit hacky, adding a new user_load now I look at it again but if there is a better way of grabbing the username of the poster then please let me know :)
> Harmony Profile Image adjustment

- core/dslmcode/shared/drupal-7.x/modules/ulmus/markdown/includes/MarkdownExtra.php
When Markdown module checks to see what 'custom' tags it should ignore, we jump in with `_webcomponents_all_tags()` to load every web component that it knows about and adds it to the list of protected or "clean" tags.
I included a patch file.  I'm not sure what our naming convention is so I just named it by issue number.
Fixes #2412
> Integrate Web components module with Markdown module

- contributing.md
"vagrant environment" was kind of a broken link, this fixes it.
> docs: fix reversed braces hyperlink syntax

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/webcomponents/modules/webcomponents_cmstags/webcomponents_cmstags.module
fixes #2508 
I think there were two reasons it wasn't correctly working.  We were passing along just the standard generic regex `/\[\S*\]/` with each replacement pattern instead of the actual pattern match.  Also, I could not get `preg_replace()` to work correctly with arrays for some reason so I switched it to a foreach loop with `str_replace()`.
In a course page, add an "elmsln_" prefixed token such as `[elmsln_section:module_1]`.  Then add a media token such as `[ciscode|rev=1|tool=elmsmedia|item=1|entity_type=node]`
> corrected replacement patterns for cis tokens.

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module
Switched the `theme()` and `drupal_alter()` function calls in `cis_lmsless.module` to allow changing of the user_block *before* it gets processed by the theme.
At the moment, the `user_block` is defined before `drupal_alter('cis_lmsless_theme_vars', $vars);` is called which means that devs are not able to make $vars changes take effect in the user flyout menu on the front.
Proposing running the alter hook before the theme is run.
> User Block Theme changes

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/cis/cis-lmsless-user.tpl.php
We've had the need in the past to edit the label and URL of the profile links in the user flyout menu. Thought it might be useful for others as well.
Proposing switching the `$userprofile` and `$userlink` to arrays so that they can be amended easier within `hook_cis_lmsless_theme_vars_alter` without the need of a patch file.
Switched `$userlink` and `$userprofile` to arrays so they can be changed in `hook_cis_lmsless_theme_vars_alter`
> Control over the user flyout login/profile links

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module
Related to #2597 
I forgot to add a default `icon` setting to the user login button. This is just adding it back.
Added the `power-settings-new` icon to the user login button which had gone AWOL.
> User flyout icon fix

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/ckeditor_custom_config.js
Fixes #2600 
Tweaked the `config.protectedSource` setting to properly format HTML comments in CKEditor.
> Updated CKEditor config

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/cis/cis-lmsless-user.tpl.php
Currently the "My Profile" link tries to appear for Anonymous users in the flyout menu, despite no data being available.
The `cis-lmsless-template.tpl.php` template is currently checking that `<?php if (!empty($username)) : ?>` however `$username` automatically defaults to "Anonymous" [here](https://github.com/elmsln/elmsln/blob/0.11.x/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module#L331) which results in a blank button (as in the screenshot below).
This PR just adds a second to check to make sure the button isn't rendered for Anonymous users.
> "My Profile" button for Anonymous users in flyout menu

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/main.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/js/main.js
> Start scrollspy after user scrolls past navigation block.

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/mooc_helper_book_nav.module
- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_nav_block/mooc_nav_block.module
Added a new hook allowing modules to alter the menu tree used in the book navigation block
Added a new hook (`hook_mooc_nav_block_alter`) which allows us to alter the menu tree used to build the navigation block on book pages. This is being used internally to develop a new feature where we need greater control over the links displayed in the sub navigation but could be useful for others.
> Mooc Nav Block Hook

- core/dslmcode/shared/drupal-7.x/modules/ulmus/h5p_tincan_bridge/h5p_tincan_bridge.module
Allow modules to prevent xAPI posts via the `tincanapi_ajax_data_alter` hook. 
We have a particular use case for this where we prevent certain verbs from actually being sent off to the LRS to cut down on the amount of data being transferred/processed there.
Tweaked it slightly from what we were using in our patch so let me know if it looks fine your end.
> Tincan API Bridge - Allow devs to prevent sends.

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_service_connection/cis_service_connection.module
Thought I would throw this one up as well while I was at it lol!
This allows anyone who's been given the `switch section context` permission to be able to switch sections (instead of limiting it just to staff/teacher roles), whilst keeping the masquerade feature limited to the original staff/teacher groupings. This allows admin to give certain roles the ability to move between sections without giving them the additional permissions associated with teachers/staff.
> Switch section context

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/entity_iframe/entity-iframe.tpl.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/entity_iframe/entity_iframe.module
Fix to allow status messages to be printed within embedded iframe content. Can be useful in some cases, such as embedded webforms, to be able to see if there are any system messages being displayed.
> Allow entity iframes to display messages.

- core/webcomponents/apps/mooc-content/mooc-content.php
Added a `hook_mooc_content_render_options_alter` hook to allow us to manually add new options to the course subnav.
Currently we're using this hook to load in a custom region where we can add new blocks containing additional buttons for the course subnav, like this:
```
function modulename_mooc_content_render_options_alter(&$content){
$blocks = block_get_blocks_by_region('operations');
$content .= drupal_render($blocks);
}
```
> Added new hook for adding new options to courses

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/ckeditor_custom_config.js
Updates to CKEditor settings to be more compatible with HAX authoring including allowing inline elements to wrap block elements and switching off auto-formatting
This PR includes fixes which prevents the issues we had with CKEditor adding loads of extra `p` and `span` tags in content and prevents it from doing weird formatting of custom webcomponents.
Related to: https://github.com/elmsln/issues/issues/915
> Updating ckeditor_custom_config.js

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/webcomponents/modules/webcomponents_cmstags/webcomponents_cmstags.module
Just switching up the cmstags endpoints into an array format so they can be easily overridden in the `webcomponents_cmstokenendpoint_alter` hook.
Also removed the token endpoint being manually added in `_webcomponents_cmstags_process` as this overwrites any hook which edited that endpoint. I've not noticed any issues after removing that my end but let me know if it's important your end.
I can see the webcomponents_cmstokenendpoint_alter hook is being used in core which will need editing but I can't tell if it's required any more: https://github.com/elmsln/elmsln/blob/837cb1bb19c15137ef052e105c7ed5e66eb3c05d/core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_service_connection/cis_service_connection.module#L180
> Tweaking cmstags endpoints structure
