- docs/domains.txt
- docs/varnish.txt
- scripts/install/handsfree/centos/centos-install.sh
- scripts/install/root/elmsln-preinstall.sh
> From phone...lol

- scripts/install/handsfree/centos/centos-install.sh
> setting up chkconfig for varnish

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/templates/book-sibling-nav.tpl.php
- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/css/mooc_styles.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
Initial theming of the book navigation menu.  I tested the changes against Safari, Chrome, Firefox.
> Book navigation theme

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/app.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/main-styles/content-styles/_content.scss
The list elements will now inherit it's styling from it's parent container.
Fixes #130
> Removed the explicitly set sizing and styles on the list elements.

- scripts/vagrant/cleanup.sh
I ran these commands on a fresh install of elmsln. I created a course http://online.elmsln.local/sing100.
Looks like it works.
> port swap to not use varnish in local dev

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access_iframe/templates/system/html.tpl.php
> Remove 'Skip to content' link in foundation_access_iframe theme

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/app.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/app.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/components/_figurelabel.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/README.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_figurelabel.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_image.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_mediasvg.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_quote.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_mediavideo.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/index.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/widgets_imagelightbox.html
This is the initial design component for the Figure Label #308
> Figure Label design component

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/template.php
Removed SVG filter for now until we can find a better solution.
> Fixed the SVG render for shortcodes.

- scripts/drush/server/user_list/README.md
- scripts/drush/server/user_list/user_list.drush.inc
https://github.com/elmsln/elmsln/issues/321
> drush user_list addition 

- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_feature/elmsmedia_feature.features.field_instance.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_feature/elmsmedia_feature.info
> SVG's need course reference

- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_feature/elmsmedia_feature.views_default.inc
> SVG's not being listed on media server #373

- docs/scale.md
This should probably be broken out into pages of a wiki or something... but this will do for now. Is this heading in the right direction?
> Added some more detail to the page

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper/mooc_helper.module
This adds a new menu callback at `mooc/book-homepage` that will look for the current section, and if that section has an outline specified, will redirect the user to that books homepage.
> Dynamic book hompage menu callback

- scripts/behat/behat.sh
- scripts/behat/composer.json
- scripts/behat/default.yaml
Attempt #7 
Added behat to the project here are the steps I used for install:
1) Install Composer and write composer.json file including extensions desired
2) Composer Install on composer.json file (update if changes have been made)
3) Write the behat.yml file -- install browser emulator (goutte or selenium)
4) Execute bin/behat --init
5) Write Feature
6) Change the Featureontext file to use Mink
7) Run bin/behat to run tests
> Added Behat to Project 

- scripts/install/root/elmsln-preinstall.sh
uses the $domains variable to properly place the changes using sed
> httpd ports in elmsln.conf (w/ varnish on)

- scripts/install/handsfree/centos7/centos7-install.sh
some sort of text editor should be installed... vim/nano... what camp are you in? should resolve issue #577
> adding vim & nano to centos7 install

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/templates/book-sibling-nav.tpl.php
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/template.php
Issue #635
PR demo:
https://youtu.be/l_0KARCRAZs
> Book Sibling Nav auto labeling

- scripts/behat/behat.sh
Tweaked behat.sh install script to replace FeaturesContext.php file so that it would use MinkContext
> Behat Script update Resolved

- docs/development/Applying-Shortcodes.md
- scripts/upgrade/elmsln-upgrade-sites.sh
This is the documentation for using tokens.
Issue #503
> Document shortcodes #503

- core/dslmcode/profiles/ulmus-7.x-1.x/modules/custom/ulmus_innovate/ulmus_innovate.info
- core/dslmcode/profiles/ulmus-7.x-1.x/ulmus.info
#749 Sorry for the extra commits, Mark and I were struggling to revert back after the last pull request.
> Added the features_builder_default

- docs/development/Drush-Targeting-Usage.md
This documents how to use drush within ELMSLN to target different parts of the system.
> Added Documentation for drush targeting in ELMSLN #790

- docs/development/Reverse-Commit-And-Push.md
This helps explain how to reverse a commit and push into one (correct) commit. This will help with making PRs more streamlined and can be a guide for beginner developers if they make mistakes with git
> Create Reverse-Commit-And-Push.md #787

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_nav_block/mooc_nav_block.module
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/app.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/app.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/main-styles/content-styles/_content.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/mooc/_mooc-book-nav.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/system/page.tpl.php
Still some work to do but it's a start.  
Note: The icons on the screenshot aren't working on my local.
> Mooc Book Nav Enhancements

- docs/development/Features-Builder.md
This is a description of how to use the feature builder module. #749
> Create Features-Builder.md #749

- scripts/drush/server/httprl_spider/httprl_spider.drush.inc
Patch was applied and testing did not brick the system
> Patched httpurl_spider #804

- docs/development/Tool-Builder.md
- mkdocs.yml
The documentation to use the tool builder.
> Using Tool-Builder

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/app.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/app.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/components/_alert-box.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/content-styles/_content.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/main-styles/content-styles/_content.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/README.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_alertbox.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_buttons.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_figurelabel.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_image.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_mediasvg.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_-_quote.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/components_mediavideo.html
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/styleguide/index.html
> Styled the alert-box. #702

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/_mooc_table-hover-responsive.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/scss/_mooc_table-striped-responsive.scss
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/tables/mooc--table.tpl.php
(exported from the WYSIWYG editor) and two of the sass files for making tables responsive to the foundation_access theme in contrib. I checked to make sure adding these files didn't crash the system, and they don't. If someone can double check that these are in the right place that would be great! This is the first time I've added styling things to the system so I want to make sure I didn't break something :P. Let me know if there is anything i need to change.
https://github.com/elmsln/elmsln/issues/785
> Added a table template #785

- docs/enduser/courses/edit.md
https://github.com/elmsln/elmsln/issues/500
> #500 Documentation

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/cis_dashboard.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/js/app.js
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/templates/cis-controlboard.tpl.php
These two commits added the Network menu item and provide tabbing abilities using angular. Added some functions and a few notes of TODO documentation.
> #405 & #921 Angular Improvements

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/templates/cis-controlboard.tpl.php
Button Panels display mock content and can switch between views. We need the data that we want to inject but the current model matches Collins' model. We need sections hooked up in materialize as well
> #405 & #921 Button Panels Display 

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/js/app.js
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/templates/cis-controlboard.tpl.php
Sorting menu items are now working via angular. Cleaned up some functions and added comments.
> #405 & #921 Sorting Working

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/js/app.js
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_dashboard/templates/cis-controlboard.tpl.php
Made the section ordering defaults year + fall / spring / summer. Orders sort properly. Made the sorting functions in app.js 2 different functions since default vars for each had to be different values
> #405 & #921 Section Ordering = Year + Fa / Sp / Su

- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/CHANGELOG.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/README.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/libraries.admin.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/libraries.api.php
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/libraries.drush.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/libraries.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/libraries.install
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/libraries.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/LibrariesAdminWebTest.test
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/LibrariesLoadWebTest.test
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/LibrariesUnitTest.test
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/LibrariesWebTestBase.test
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/libraries/example_info_file.libraries.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/modules/libraries_test_module/libraries_test_module.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/modules/libraries_test_module/libraries_test_module.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/libraries/tests/themes/libraries_test_theme/libraries_test_theme.info
Updated the Libraries module and tested to make sure it didn't break anything in the materialize branch. Currently we don't have many libraries loaded via the Libraries API as only 3 are detected when looking at this update.
> #972 Libraries Update

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_cdn/elmsln_cdn.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/fastclick/add_version_regex-2755133-2.patch
- core/dslmcode/shared/drupal-7.x/modules/ulmus/fastclick/fastclick.module
Added version regex support @ https://www.drupal.org/node/2755133.
> #982 Version Regex Patch

- core/dslmcode/shared/drupal-7.x/modules/ulmus/h5p_tincan_bridge/h5p_tincan_bridge_pass_downstream_via_POST-2755205-2.patch
Added the patch for the downstream pass of data via POST in h5p tincan bridge
> #974 Added patch file from D.O.

- core/dslmcode/shared/drupal-7.x/modules/ulmus/features_override/features_override.export.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/features_override/features_override_for_each_now_obj_or_arr-2760807-2.patch
Added the check for `$default` being a valid datatype to be put through the foreach loop. Also closed the first foreach loop for validation. Still need to see if the First bug exists for the issue (#931)
> #931 Second Bug in Issue Sqashed

- scripts/frontend/frontend-install.sh
- scripts/frontend/nodejs-install.sh
Needs testing.  Should install Node Version Manager, then the latest version of NPM.
run `bash elmsln/scripts/frontend/frontend-install.sh`
then `npm`
You should see npm documentation in the terminal.
> Added an install script for nodejs.

- core/dslmcode/profiles/cis-7.x-2.x/modules/features/cis_displays/cis_displays.install
- core/dslmcode/profiles/cis-7.x-2.x/modules/features/cis_displays/cis_displays.views_default.inc
Visual Listing is gone and the update hooks have been written to get this running.
> #1049 Removed Visual Listing

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_features/mooc_cis_ux/mooc_cis_ux.install
- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_features/mooc_cis_ux/mooc_cis_ux.views_default.inc
Adding Caching to Course / MOOC. Added update hooks.
> #1036 Course / MOOC Caching

- core/dslmcode/profiles/editorial-7.x-1.x/modules/features/editorial_displays/editorial_displays.install
- core/dslmcode/profiles/editorial-7.x-1.x/modules/features/editorial_displays/editorial_displays.views_default.inc
- core/dslmcode/profiles/editorial-7.x-1.x/modules/features/editorial_journal_entry/editorial_journal_entry.install
- core/dslmcode/profiles/editorial-7.x-1.x/modules/features/editorial_journal_entry/editorial_journal_entry.views_default.inc
- core/dslmcode/profiles/editorial-7.x-1.x/modules/features/editorial_story_seeds/editorial_story_seeds.install
- core/dslmcode/profiles/editorial-7.x-1.x/modules/features/editorial_story_seeds/editorial_story_seeds.views_default.inc
Added proper caching for Blog. Added update hooks as well.
> #1036 Blog Caching

- core/dslmcode/profiles/ecd-7.x-1.x/modules/features/ecd_displays/ecd_displays.install
- core/dslmcode/profiles/ecd-7.x-1.x/modules/features/ecd_displays/ecd_displays.views_default.inc
Caching for Comply is complete. Changed files in ECD profile to have high 6day caching
> #1036 Comply Caching Complete

- core/dslmcode/profiles/cis-7.x-2.x/themes/cis_foundation_access/css/cis_styles.css
- core/dslmcode/profiles/cis-7.x-2.x/themes/cis_foundation_access/template.php
> beautify course page filter headings

- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/LICENSE.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/README.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/css/puzzler.css
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/puzzler.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/puzzler.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/puzzler.install
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/puzzler.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/puzzler_cache.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/puzzler/puzzler_settings.inc
This module is really cool and with the current update to dev it works without throwing the error message in #1053.
> #1053 Added Puzzler

- core/dslmcode/profiles/elmsmedia-7.x-1.x/elmsmedia.info
- core/dslmcode/profiles/elmsmedia-7.x-1.x/elmsmedia.install
Added update hook and its dependency on the .info file.
> #1103 Added modernizer to elmsmedia

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/a11y/a11y.module
Patched the current code. Will need to add the patch to patches dir for reference once d.o. patch is accepted.
> #1123 Added Patch to a11y

- docs/systems/authority/people.md
This is what the People distro is about from what I can gather! I've just included 'what is envisioned' cause I don't know what's in there at the moment and not sure how widely used it is
> People distro vision

- Vagrantfile
- scripts/vagrant/handsfree-vagrant.sh
Can you accept this so I can do a quick spot check? I had to test this against my own repo since there were some absolute urls in the vagrant up command.
Should fix #736
> Spot check on pr

- core/dslmcode/shared/drupal-7.x/modules/ulmus/tincanapi/modules/tincanapi_links/new_jquery_click_tracking_fix-2792311-2.patch
Recorded the tincan_links patch that is on drupal.org.
> #1190 Added tincan_links patch for record

- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/LICENSE.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/README.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/plugins/views_content_cache/base.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/plugins/views_content_cache/comment.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/plugins/views_content_cache/node.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/plugins/views_content_cache/node_only.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/plugins/views_content_cache/og.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/plugins/views_content_cache/votingapi.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/tests/views_content_cache.test
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/views/views_content_cache.views.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/views/views_content_cache_plugin_cache.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/views_content_cache.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/views_content_cache.install
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views_content_cache/views_content_cache.module
Added the Views Content Cache module so that we can cache by type.
> #1216 Added Views Content Cache Module

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
- docs/development/Drush-Targeting-Usage.md
This will help developers create dummy content via drush
> Added Devel Generate to Useful Commands

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/js/app.js
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/js/components/clipboardjs.js
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/js/dist/app.js
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/template.php
> Changed clipboardjs tooltips to use Materialize toast notifications.

- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/modules/git_book_gb/git_book_gb.module
that were not an array, hence the array_keys error and the reason the whole book wasn't getting pulled in
> missed a whole group of nodes

- core/dslmcode/profiles/cpr-7.x-1.x/modules/features/cpr_user/cpr_user.features.field_instance.inc
- core/dslmcode/profiles/cpr-7.x-1.x/modules/features/cpr_user/cpr_user.info
- core/dslmcode/profiles/cpr-7.x-1.x/modules/features/cpr_user/cpr_user.strongarm.inc
- core/dslmcode/profiles/cpr-7.x-1.x/themes/cpr_foundation_access/templates/user-profile.tpl.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.info
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.strongarm.inc
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/system/page.tpl.php
@heyMP and I are going to fix the sass stack tomorrow. Until then this is a good start.
> Start to the user profile

- scripts/vagrant/cleanup.sh
Can be easily added to running vm
> removing front end stack for now

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/template.php
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/template.php
> Remove title from a page when a gitbook markdown filter is present

- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_critique/cle_critique.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_core/elmsln_core.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/cors/LICENSE.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/cors/README
- core/dslmcode/shared/drupal-7.x/modules/ulmus/cors/cors.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/cors/cors.module
This will allow for preflight calls which take place in headless apps.
> Allow HTTP OPTIONS request for anon users.

- docs/development/DNS-Setup-Example.md
Fixes #
Setup DNS on example hosting service before ELMS:LN is installed.
> i1288 Document DNS Setup

- core/dslmcode/stacks/interact/sites/all/modules/local_contrib/leaflet/resolve_issues_to_leaflet_widget-2828094-3.patch
- core/dslmcode/stacks/interact/sites/all/modules/local_contrib/leaflet_widget/js_for_compatibility-2828085-3.patch
Committing patches to leaflet and leaflet_widget modules, related to issue #1436
> Patches to leaflet and leaflet_widget module

- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment.service.ts
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment-list/assignment-list.component.css
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment-list/assignment-list.component.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment.component.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment.component.ts
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/login/login.component.ts
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_assignment/cle_assignment.module
I made some changes to the start and end dates in the assignment.module
> Changed the assignments dates to ISO formatting.

- core/dslmcode/shared/drupal-7.x/modules/ulmus/h5p_tincan_bridge/h5p_tincan_bridge-reduce_number_of_posts-2589945-3.patch
- core/dslmcode/shared/drupal-7.x/modules/ulmus/tincanapi/tincanapi-support_alternate_request_methods-2821235-3.patch
Fixes #
Patched tincanapi and h5p_tincan_bridge modules on d.o. and pushed the patches to the appropriate elmsln directories.
> #1377 tincanapi patch clean up w/ drupal.org

- docs/development/Vagrant-Step-by-Step-setup.md
This link was going to a Read the docs 404 page :)
> Updating a broken link to the install page

- scripts/install/handsfree/ubuntu16/ubuntu16-install.sh
- scripts/install/root/elmsln-create-accounts.sh
correctly installs yaml, and fixes sudo prompt
> Fixes Ubuntu 16 install

- core/dslmcode/profiles/cle-7.x-2.x/modules/cle_custom/cle_api/cle_api.module
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment.service.ts
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment.ts
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment-form/assignment-form.component.css
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment-form/assignment-form.component.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment-form/assignment-form.component.ts
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/assignment/assignment.component.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/projects/project-item/project-item.component.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_app/app/src/app/projects/projects-list/projects-list.component.ts
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_assignment/cle_assignment.module
@btopro I made more changes to the cle_assignments & cle_api modules. You can leave this pull request open until you're ready to work on the profile in case I make more changes.
> CLE Module changes

- core/dslmcode/profiles/icor-7.x-1.x/icor.install
- core/dslmcode/profiles/icor-7.x-1.x/modules/features/icor_interactive_player/icor_interactive_player.features.field_instance.inc
- core/dslmcode/profiles/icor-7.x-1.x/modules/features/icor_ux/icor_ux.features.field_base.inc
- core/dslmcode/profiles/icor-7.x-1.x/modules/features/icor_ux/icor_ux.features.field_instance.inc
Fixes #
ICOR now supports multiple course selection for it’s course field. Features affected:
icor_ux
icor_interactive_player
> #1298 Multiple Course Select ICOR

- Vagrantfile
I also added the .name property so that virtualbox calls it elmsln. Helps with packaging if we do that later.
> Our pre-seeded box with installer

- README.md
> Found Typo

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
> h5p bullet point needs to not show up

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
> sync master and 7

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/template.php
> duration as timer value icon

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/mooc_helper_book_nav.module
> hide outline nav for anonymous users

- core/dslmcode/profiles/elmsmedia-7.x-1.x/elmsmedia.info
- core/dslmcode/profiles/elmsmedia-7.x-1.x/elmsmedia.install
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_image/elmsmedia_image.features.field_instance.inc
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_image/elmsmedia_image.info
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_static_content/elmsmedia_static_content.features.field_base.inc
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_simple_filter/elmsln_simple_filter.features.filter.inc
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_simple_filter/elmsln_simple_filter.info
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_simple_filter/elmsln_simple_filter.module
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/node/audio/node--inherit--audio.tpl.php
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/node/elmsmedia-image/node--inherit--elmsmedia-image--accessible-fallback.tpl.php
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/node/video/node--inherit--video.tpl.php
> minor media update stuff

- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_assignment/cle_assignment.module
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_project/cle_project.module
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_submission/cle_submission.module
- core/dslmcode/profiles/cpr-7.x-1.x/themes/cpr_foundation_access/template.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/cis_connector.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_lmsless/cis_lmsless.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/elmsln_api/elmsln_api.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/cis_service_restws/cis_service_restws.module
- scripts/drush-create-site/drush-create-site
- scripts/install/handsfree/ubuntu16/ubuntu16-install.sh
most pull via master, there's 2 critical (small) bugs in the 0.7.0 we just discovered making development very difficult w/o their resolving. Also some bugs associated w/ ssl based deployments
> critical add to master

- docs/development/Vagrant-Step-by-Step-setup.md
Added reference to issue. This may be OS specific, but good to have.
> #1843 APDQC SQL Restart Error Noted in Vagrant Docs

- LICENSE.md
Really minor, but it caught my eye when I was browsing through files.
> Update to 2017

- docs/development/polymer-cli-step-by-step.md
This shows how to get polymer-cli setup for webcomponent's local testing.
Fixes #
> #1938 Document polymer-cli local install

- mkdocs.yml
> #1938 Added Polymer CLI reference to mkdocs.yml

- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_control/LICENSE.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_control/flood_control.admin.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_control/flood_control.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_control/flood_control.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/LICENSE.txt
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/flood_unblock.admin.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/flood_unblock.drush.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/flood_unblock.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/flood_unblock.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/flood_unblock_services/flood_unblock_services.info
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/flood_unblock_services/flood_unblock_services.module
- core/dslmcode/shared/drupal-7.x/modules/ulmus/flood_unblock/flood_unblock_services/flood_unblock_services.services.inc
Fixes #1965 
We've added two modules that should help w/ automatic logout; we haven't enabled them though.
> Automatic lockout after 5 attempts - admin controls #1965

- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/git_book.module
- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/modules/git_book_gb/git_book_gb.module
gitbook now uses path aliases to name files.
> Updates we made to gitbook

- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/modules/git_book_gb/git_book_gb.module
> added more preg_replacements for the gitbook parser.

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/css/mooc_styles.css
Temporary fixes for #CSS sticky-nav problem #1998 / Adjusted width, removed border.
#1998
> Removed border, adjusted width

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/css/mooc_styles.css
And all is right with the world.  Undid all changes.
fixes #1998
> undo the scroll spy ux changes.

- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_h5p/elmsmedia_h5p.info
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_h5p/elmsmedia_h5p.install
- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/features/elmsmedia_h5p/elmsmedia_h5p.strongarm.inc
Adjusted these features to default FALSE ("user H5P hub" and "automatically contribute usage statistics") by default. 
Fixes #1990
> Roll these settings into a feature

- Vagrantfile
> Changed to 0.9.x

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_simple_filter/elmsln_simple_filter.features.filter.inc
> Revert "Add hyperlink functionality to simple text format #2012 -- Pull request"

- README.md
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-comments-recent/src/lrnapp-comments-recent/drupal-comment.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-comments-recent/src/lrnapp-comments-recent/lrnapp-comments-recent.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-open-studio/bower_components/lrndesign-gallerycard/lrndesign-gallerycard.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-open-studio/src/lrnapp-open-studio/lrnapp-open-studio.html
In the process of styling both.
> Open Studio and Recent Comments

- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-comments-recent/src/lrnapp-comments-recent/drupal-comment.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-comments-recent/src/lrnapp-comments-recent/lrnapp-comments-recent.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-open-studio/bower_components/lrndesign-gallerycard/lrndesign-gallerycard.html
styled recent comments - done
continued styling open studio
> open studio and recent comments updated

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/tweaks.css
> Added a small css override to force inline mathjax

- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-open-studio/bower_components/lrndesign-gallerycard/lrndesign-gallerycard.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-open-studio/src/lrnapp-open-studio/lrnapp-open-studio.html
> lrnapp-open-studio / lrndesign-gallerycard

- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/lrnapp-studio-submission.php
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/manifest.json
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-button.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/services/CleOpenStudioAppSubmissionService.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/webcomponents/modules/webcomponents_app/webcomponents_app.module
```
<lrnapp-studio-submission-button assignment-id="[[id]]" submission="{{submission}}" end-point="[[endPoint]]" csrf-token=[[csrfToken]]></lrnapp-studio-submission-button>
```
> Studio submission button

- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/package.json
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-edit-file.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-edit-files.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-edit-links.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-edit.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-media-editoverlay.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-page.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/services/CleOpenStudioAppSubmissionService.php
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/elmsln_api/elmsln_api.module
> Studio File Fields

- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-display.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-edit.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-page.html
- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/services/CleOpenStudioAppSubmissionService.php
- core/dslmcode/profiles/cle-7.x-2.x/modules/features/cle_submission/cle_submission.module
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_student_filter/elmsln_student_filter.features.filter.inc
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/features/elmsln_student_filter/elmsln_student_filter.info
- Fixed submission text saving
- Added submission type to submission meta attributes
- starting moving ajax stuff to parent component `lrnapp-studio-submission-page` so we can add more displays like full display, edit, critique, edit critique.
> Studio Changes

- core/dslmcode/profiles/cle-7.x-2.x/modules/apps/cle_open_studio_app/apps/lrnapp-studio-submission/src/lrnapp-studio-submission/lrnapp-studio-submission-display.html
I've added a toggle class for margin on rotate buttons to fix the overlap.
I've added transform scale through style attribute for flipping image.
Fixes #2226
> fixes overlap, and flip style

- Vagrantfile
> 0.10.x for new development

- CODE_OF_CONDUCT.md
This is a 1st draft forked from Contributor Covenant Code of Conduct with influence from https://policy.psu.edu/policies/AD85
#2308
> initial draft of CoC #2308

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper/mooc_helper.module
- docs/systems/service/courses.md
- docs/systems/service/courses/routes.md
find active book homepage and render it through lrnapp-book.  
Refactored `mooc/book-homepage` to use the same logic.  
Added a documentation page.
> Added a dynamic route `mooc/lrnapp-book`

- core/dslmcode/profiles/elmsmedia-7.x-1.x/modules/apps/elmsmedia_apps/apps/elmsmedia-dashboard
> added elmsmedia-dashboard link to elmsmedia_apps module.

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper/mooc_helper.module
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/main.css
> Add Print Outline Button

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/system/html--user.tpl.php
- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/templates/system/page--user.tpl.php
> #2387 as it's own branch until confirmed

- core/dslmcode/profiles/mooc-7.x-1.x/themes/mooc_foundation_access/css/mooc_styles.css
> added 100% to iframes in mooc content.

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/webcomponents/modules/webcomponents_token/webcomponents_token.info
- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/webcomponents/modules/webcomponents_token/webcomponents_token.module
- core/webcomponents/elements/drupal-token/drupal-token.html
This gets a non-functional but needs deeper testing drupal-token tag into the stack
> #2448 initial work towards this

- CODE_OF_CONDUCT.md
This Pull Request is a bit of an experiment.
As a newcomer, I'm not actually sure what the community standards are in the ELMS:LN project.
But I guess I'd be pretty taken aback if, qua Code of Conduct, the community standard here is "Only promoting and utilizing Free Open Source Solutions (FOSS)".
I'm utilizing a proprietary solution MacBook Air to compose this Pull Request. That's not actually out of norm with ELMS:LN community standards, is it? I'm utilizing GitHub (alas, proprietary) to host this changeset and resulting Pull Request. That too is just fine, yes?
:)
> docs(code_of_conduct): rm only using FOSS as community standard

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/admin.css
> fixed Bad CSS selector #2502

- core/dslmcode/shared/drupal-7.x/themes/elmsln_contrib/foundation_access/css/main.css
> #2498 CSS updates

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_tokens/cis_tokens.module
You can add the `:raw` to an elmsln_section token and it won't add the outline indicator to it.
Fixes #2588
> Added a raw flag to elmsln_section tokens.

- core/dslmcode/stacks/courses/sites/all/modules/local_contrib/git_book/modules/git_book_gb/git_book_gb.module
This is a terrible solution but it was the best I could do 🤷‍♂️
> temp fix for an i18n character in gitbook parser.

- README.md
Fixes #
Removed the badges and sponsors.
> Removed badges and sponsors

- README.md
Removed sponsor section at the request of btopro
Fixes #
> Removed Sponsors

- README.md
> Removed backers and sponsors

- README.md
Changed the PHP version section to display that versions 7.1+ are supported.
Fixes #
> Updated PHP version to reflect 7.1+

- README.md
Fixes #2654 Updated the PHP version number to reflect the correct version (7.1+)
> Updated the PHP version number to read 7.1+

- README.md
> Update README.md changed to 0.11.x

- core/dslmcode/shared/drupal-7.x/modules/ulmus/views/handlers/views_handler_area_result.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views/modules/field/views_handler_field_field.inc
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views/views-handler-field-relationship-fix.patch
- core/dslmcode/shared/drupal-7.x/modules/ulmus/views/views-handler-pagination-fix.patch
Fixes an issue with pagination where an empty result set could result in a negative `$start` value.
> Pagination fix

- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper/mooc_helper.module
- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_helper_book_nav/mooc_helper_book_nav.module
- core/dslmcode/profiles/mooc-7.x-1.x/modules/mooc_custom/mooc_nav_block/mooc_nav_block.module
Adding in a few hooks to allow devs to amend the course navigation before its rendered.
> Adding in Mooc hooks

- core/dslmcode/stacks/discuss/sites/all/modules/local_contrib/harmony_core/harmony-post-template-updates.patch
- core/dslmcode/stacks/discuss/sites/all/modules/local_contrib/harmony_core/theme/harmony-post.tpl.php
Editing the HTML structure of `harmony-post.tpl`
> Updating the `harmony-post.tpl` file.

- core/dslmcode/shared/drupal-7.x/modules/elmsln_contrib/cis_connector/modules/core/cis_filter/cis_filter.module
- core/dslmcode/shared/drupal-7.x/settings/shared_settings.php
Related: https://github.com/elmsln/issues/issues/956
Adding new shared setting option for customising the timeout on certain cis_filter queries. Set the default to 5000 as discussed.
Let me know if you wanted me to do anything else here.
> cis_filter timeout shared setting update
